name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify --logLevel info
      working-directory: ./we.r.robots-blog

    - name: Sync files to S3 
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
        local_dir: 'we.r.robots-blog/public/'
        s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        s3_sync_path: 'public/'  # Adjust if you need a specific directory structure in S3
      env:
        AWS_REGION: 'us-east-1'  # Specify your bucket's region

