name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify --verbose

    - name: Deploy to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        folder: public
        bucket: ${{ secrets.AWS_S3_BUCKET }}
        key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_REGION }}
