name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify
      working-directory: 'we.r.robots-blog'

    - name: Sync files to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        source_dir: 'we.r.robots-blog/public/'
        aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

